spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://mysql:3306/medical_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: nbuDBpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/medical-realm
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  mail:
    from: no-reply@your-azure-domain.com
server:
  port: 8080
cloudinary:
  cloud-name: Medicine-app
  api-key: 916245136867445
  api-secret: 04s3evY6JbCtD5M8wMdKHcD8tgU
keycloak:
  auth-server-url: http://keycloak:8080/auth
  realm: medical-realm
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
sendgrid:
  api:
    key: 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
  from:
    email: no-reply@your-azure-domain.com