spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/medical_db?createDatabaseIfNotExist=true
    username: root
    password: nbuDBpass
    driver-class-name: com.mysql.cj.jdbc.Driver